# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub:
    """============================================================
    CLIENT -> APPLICATION SERVER
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.login = channel.unary_unary(
                '/inventory.ClientService/login',
                request_serializer=inventory__pb2.LoginRequest.SerializeToString,
                response_deserializer=inventory__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.logout = channel.unary_unary(
                '/inventory.ClientService/logout',
                request_serializer=inventory__pb2.LogoutRequest.SerializeToString,
                response_deserializer=inventory__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.post = channel.unary_unary(
                '/inventory.ClientService/post',
                request_serializer=inventory__pb2.PostRequest.SerializeToString,
                response_deserializer=inventory__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.get = channel.unary_unary(
                '/inventory.ClientService/get',
                request_serializer=inventory__pb2.GetRequest.SerializeToString,
                response_deserializer=inventory__pb2.GetResponse.FromString,
                _registered_method=True)


class ClientServiceServicer:
    """============================================================
    CLIENT -> APPLICATION SERVER
    ============================================================

    """

    def login(self, request, context):
        """Authenticate a user and create a session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def logout(self, request, context):
        """End an authenticated session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def post(self, request, context):
        """Send an operation such as placing an order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Retrieve information such as inventory or order history.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'login': grpc.unary_unary_rpc_method_handler(
                    servicer.login,
                    request_deserializer=inventory__pb2.LoginRequest.FromString,
                    response_serializer=inventory__pb2.LoginResponse.SerializeToString,
            ),
            'logout': grpc.unary_unary_rpc_method_handler(
                    servicer.logout,
                    request_deserializer=inventory__pb2.LogoutRequest.FromString,
                    response_serializer=inventory__pb2.StatusResponse.SerializeToString,
            ),
            'post': grpc.unary_unary_rpc_method_handler(
                    servicer.post,
                    request_deserializer=inventory__pb2.PostRequest.FromString,
                    response_serializer=inventory__pb2.StatusResponse.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=inventory__pb2.GetRequest.FromString,
                    response_serializer=inventory__pb2.GetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService:
    """============================================================
    CLIENT -> APPLICATION SERVER
    ============================================================

    """

    @staticmethod
    def login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.ClientService/login',
            inventory__pb2.LoginRequest.SerializeToString,
            inventory__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.ClientService/logout',
            inventory__pb2.LogoutRequest.SerializeToString,
            inventory__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.ClientService/post',
            inventory__pb2.PostRequest.SerializeToString,
            inventory__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.ClientService/get',
            inventory__pb2.GetRequest.SerializeToString,
            inventory__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AppServerServiceStub:
    """============================================================
    APPLICATION SERVER INTERNAL SERVICE
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.processBusinessRequest = channel.unary_unary(
                '/inventory.AppServerService/processBusinessRequest',
                request_serializer=inventory__pb2.BusinessRequest.SerializeToString,
                response_deserializer=inventory__pb2.StatusResponse.FromString,
                _registered_method=True)


class AppServerServiceServicer:
    """============================================================
    APPLICATION SERVER INTERNAL SERVICE
    ============================================================

    """

    def processBusinessRequest(self, request, context):
        """Generic business-logic entry point.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'processBusinessRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.processBusinessRequest,
                    request_deserializer=inventory__pb2.BusinessRequest.FromString,
                    response_serializer=inventory__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.AppServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.AppServerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppServerService:
    """============================================================
    APPLICATION SERVER INTERNAL SERVICE
    ============================================================

    """

    @staticmethod
    def processBusinessRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.AppServerService/processBusinessRequest',
            inventory__pb2.BusinessRequest.SerializeToString,
            inventory__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LLMServiceStub:
    """============================================================
    APPLICATION SERVER -> LLM SERVER
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLLMAnswer = channel.unary_unary(
                '/inventory.LLMService/getLLMAnswer',
                request_serializer=inventory__pb2.LLMRequest.SerializeToString,
                response_deserializer=inventory__pb2.LLMAnswerResponse.FromString,
                _registered_method=True)


class LLMServiceServicer:
    """============================================================
    APPLICATION SERVER -> LLM SERVER
    ============================================================

    """

    def getLLMAnswer(self, request, context):
        """Send an AI task and its context to the LLM server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLLMAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.getLLMAnswer,
                    request_deserializer=inventory__pb2.LLMRequest.FromString,
                    response_serializer=inventory__pb2.LLMAnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService:
    """============================================================
    APPLICATION SERVER -> LLM SERVER
    ============================================================

    """

    @staticmethod
    def getLLMAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.LLMService/getLLMAnswer',
            inventory__pb2.LLMRequest.SerializeToString,
            inventory__pb2.LLMAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
